displayName: Lagom Java
description: Sample for building Lagom Reactive microservice in Java
tags: ["Java", "Maven",]
globalMemoryLimit: 2674Mi
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
projectType: "docker"
language: "java"
